baseURL = 'https://aieideas.com/'
languageCode = 'en-us'
title = 'An Inspired Engineer'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
description = "Writing about Networking, Operation Systems, Distributed Systems, Linux Kernel."
googleAnalytics = "G-805GYGRJQH"

theme = 'auto'
colorPalette = 'default'
hideHeader = false

homeIntroTitle = 'Hey, I’m Abolfazl!'
homeIntroContent = """
I'm interested in systems programming, OS internals, and concurrency, 
with experience and passionate about building efficient system-level solutions and networking. 
I'm focusing on Vortex L4 load-balancing, and developing kdht a Kademlia Distributed Hash Table project.
"""

# Collection to display on home
homeCollectionTitle = 'Blog'
homeCollection = 'posts'

paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

breadcrumbs = true

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/aabolfazl"

[[params.social]]
name = "telegram"
url = "https://t.me/knowpow"

[[params.social]]
name = "github"
url = "https://github.com/aabolfazl"

[[params.social]]
name = "X"
url = "https://twitter.com/_AbolfazlAbbasi"

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "blog"
url = "/posts"

[[params.menu]]
name = "now"
url = "/now"

[[params.menu]]
name = "reading list"
url = "/reading-list"

[markup]
[markup.highlight]
style = 'algol'

[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"